/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { WineChain } from './WineChain.js';
export * as factories from './factories/index.js';
export { WineChain__factory } from './factories/WineChain__factory.js';